sudo: required
language: generic 

services: 
 - docker 

before_install: 
  - docker build -t nerosegnofic/docker-react -f Dockerfile.dev .

scripts: 
  - docker run -e CI=true nerosegnofic/docker-react npm run test
